ARG NODE_VERSION=18.18-alpine
ARG PLATFORM=amd64
#ARG PLATFORM=arm64v8
FROM ${PLATFORM}/node:${NODE_VERSION}
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ./frontend/package*.json ./
RUN npm install -g npm@10.1.0
RUN npm install
COPY ./frontend .
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]

